export enum Zone {
  "Pereira" = "Pereira",
  "Zona Centro" = "Zona Centro",
  "Polanco" = "Polanco",
  "Coyoacán" = "Coyoacán",
  "Colonia Centro" = "Colonia Centro",
  "Jardines del Pedregal" = "Jardines del Pedregal",
  "San José" = "San José",
  "Vallarta Poniente" = "Vallarta Poniente",
  "Lomas de Hidalgo" = "Lomas de Hidalgo",
  "Galerías" = "Galerías",
  "Cali" = "Cali",
  "Paseo de Querétaro Liverpool Bx" = "Paseo de Querétaro Liverpool Bx",
  "Tuxtepec" = "Tuxtepec",
  "Liverpool Centro comercial Santa Fe" = "Liverpool Centro comercial Santa Fe",
  "Liverpool Parque Delta" = "Liverpool Parque Delta",
  "Surco" = "Surco",
  "León de los Aldama" = "León de los Aldama",
  "Monterrey" = "Monterrey",
  "Centro" = "Centro",
  "Jardines de Santa Mónica" = "Jardines de Santa Mónica",
  "Andares Puerta de Hierro" = "Andares Puerta de Hierro",
  "Lauret Oficinas y Apartamentos" = "Lauret Oficinas y Apartamentos",
  "Arboledas de Guadalupe" = "Arboledas de Guadalupe",
  "San Isidro" = "San Isidro",
  "Bogotá" = "Bogotá",
  "VERACRUZ" = "VERACRUZ",
  "San Isidro / Lima" = "San Isidro / Lima",
  "Ex Hacienda Candiani" = "Ex Hacienda Candiani",
}

export enum Services {
  "fullprimera" = "fullprimera",
  "fullseguimiento" = "fullseguimiento",
  "refinamiento" = "refinamiento",
  "futura" = "futura",
  "fullrecolocacion" = "fullrecolocacion",
  "nmt_rx" = "nmt_rx",
  "limpiezaplan" = "limpiezaplan",
  "limpiezayblanqplan" = "limpiezayblanqplan",
  "rescan" = "rescan",
  "nmt60" = "nmt60",
  "fullfinal" = "fullfinal",
  "retenedorfijo" = "retenedorfijo",
  "videollamada" = "videollamada",
  "scan_retenedor" = "scan_retenedor",
  "interpretacion_plan" = "interpretacion_plan",
  "nmt_resina" = "nmt_resina",
  "nmt_brackets" = "nmt_brackets",
  "nmt_limpieza" = "nmt_limpieza",
  "nmt30" = "nmt30",
}

export enum CenterType {
  "Centro Aliado" = "Centro Aliado",
  "Doctores Moons" = "Doctores Moons",
  "Centro Moons" = "Centro Moons",
  "Liverpool" = "Liverpool",
  "Citas Valoración" = "Citas Valoración",
}
